"""Write requirements.lock: every package AKSAL actually pulls in, pinned.

pyproject pins the DIRECT dependencies, which fixes behaviour. This fixes the
build: it walks the dependency graph from those roots and pins everything it
reaches, so a build made months from now installs the same tree rather than
whatever the resolver picks on the day.

Generated from the environment rather than by a resolver, deliberately. This is
the environment the accuracy figures in the README were measured in, so it is
the one worth reproducing -- and it needs no extra tooling to regenerate.

    python packaging/make_lock.py

Extras are walked too, so demucs and its tree appear; the frozen build excludes
them, but someone installing `aksal[separate]` should get the same versions.
"""
from __future__ import annotations

import sys
import tomllib
from importlib.metadata import PackageNotFoundError, distribution, version
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def canonical(name: str) -> str:
    return name.lower().replace("_", "-").split("[")[0].strip()


def requirement_names(spec: str) -> str:
    """The bare package name from a requirement line."""
    for sep in (";", "==", ">=", "<=", "~=", "!=", ">", "<", "[", " ", "("):
        spec = spec.split(sep)[0]
    return canonical(spec)


def walk(roots: list[str]) -> dict[str, str]:
    """Every distribution reachable from `roots`, with its installed version."""
    seen: dict[str, str] = {}
    # requirement_names, not canonical: the roots come from pyproject and carry
    # version specifiers ("numpy==2.2.6"), which are not package names. Getting
    # this wrong produced a lock file containing exactly one package.
    todo = [requirement_names(r) for r in roots]
    missing: list[str] = []

    while todo:
        name = todo.pop()
        if name in seen or name == "aksal":
            continue
        try:
            seen[name] = version(name)
            dist = distribution(name)
        except PackageNotFoundError:
            missing.append(name)
            continue
        for req in dist.requires or []:
            # Skip requirements gated behind an extra we are not asking for:
            # they are optional by definition and often not installed.
            if "extra ==" in req:
                continue
            todo.append(requirement_names(req))

    for name in missing:
        print(f"  note: {name} is declared but not installed; not pinned",
              file=sys.stderr)
    return seen


def main() -> int:
    project = tomllib.load(open(ROOT / "pyproject.toml", "rb"))["project"]
    roots = list(project["dependencies"])
    for name, reqs in project.get("optional-dependencies", {}).items():
        if name != "all":
            roots += reqs

    resolved = walk(roots)
    lines = [
        "# Generated by packaging/make_lock.py -- do not edit by hand.",
        "#",
        "# Every package AKSAL reaches, pinned, so a build reproduces rather",
        "# than inheriting whatever the resolver picks that day. torch and",
        "# torchaudio still need the CPU index, or pip fetches several GB of",
        "# unused CUDA:",
        "#",
        "#   pip install -r requirements.lock \\",
        "#       --extra-index-url https://download.pytorch.org/whl/cpu",
        "",
    ]
    lines += [f"{name}=={ver}" for name, ver in sorted(resolved.items())]
    out = ROOT / "requirements.lock"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out.name}: {len(resolved)} packages pinned")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
